// <auto-generated />
using System;
using LeaveManagmentSystem.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveManagmentSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702105414_AddedAllConfigurationForEntity")]
    partial class AddedAllConfigurationForEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.AttendenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<TimeOnly?>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("HoursWorked")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CheckIn = new TimeOnly(9, 0, 0),
                            CheckOut = new TimeOnly(18, 0, 0),
                            Date = new DateOnly(2024, 1, 15),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            HoursWorked = 9.0,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Date = new DateOnly(2024, 1, 16),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            CheckIn = new TimeOnly(9, 30, 0),
                            Date = new DateOnly(2024, 1, 17),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsActive = true,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.LeaveBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Pending")
                        .HasColumnType("int");

                    b.Property<int>("TotalAllotted")
                        .HasColumnType("int");

                    b.Property<int>("Used")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            LeaveTypeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Pending = 0,
                            TotalAllotted = 12,
                            Used = 3,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            LeaveTypeId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Pending = 0,
                            TotalAllotted = 15,
                            Used = 3,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            LeaveTypeId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Pending = 0,
                            TotalAllotted = 20,
                            Used = 0,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            EndDate = new DateOnly(2024, 2, 3),
                            LeaveTypeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Reason = "Fever and cold",
                            StartDate = new DateOnly(2024, 2, 1),
                            Status = 0,
                            TotalDays = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            EndDate = new DateOnly(2024, 2, 7),
                            LeaveTypeId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Reason = "Family function",
                            ReviewRemarks = "Approved",
                            ReviewedBy = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            StartDate = new DateOnly(2024, 2, 5),
                            Status = 1,
                            TotalDays = 3,
                            UpdatedAt = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCarryForwardAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDaysPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsCarryForwardAllowed = false,
                            MaxDaysPerYear = 12,
                            Name = "Sick Leave"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsCarryForwardAllowed = false,
                            MaxDaysPerYear = 15,
                            Name = "Casual Leave"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsCarryForwardAllowed = true,
                            MaxDaysPerYear = 20,
                            Name = "Earned Leave"
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.Permissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "View leave requests",
                            Name = "leaves.view"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Apply for leave",
                            Name = "leaves.apply"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Approve or reject leave requests",
                            Name = "leaves.approve"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "Cancel own leave request",
                            Name = "leaves.cancel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Description = "Export leave reports",
                            Name = "leaves.export"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Description = "View own attendance",
                            Name = "attendance.view_own"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Description = "View team attendance",
                            Name = "attendance.view_team"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Description = "Check in and check out",
                            Name = "attendance.checkin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Description = "View all users",
                            Name = "users.view"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Create users",
                            Name = "users.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "Edit users",
                            Name = "users.edit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "Manage leave types",
                            Name = "leavetypes.manage"
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("Role", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Role = 0
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@company.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$11$Xb28.8k4vcXEn4T07b12W.T5iLCaGkMQVSVJIgmeFNDPMaTFWX8My",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "eng.manager@company.com",
                            FullName = "Engineering Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$.LpJmzbmxrTPvEbEFbQRn.hRSQsMfr3HFaWosTJNiOond1EeSDGjC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "john.doe@company.com",
                            FullName = "John Doe",
                            IsActive = true,
                            ManagerId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PasswordHash = "$2a$11$6sGnr3PlZo3yVl7wP8Y1hu41G0dVZRGnWiz4dhSlQ4oj1dgHkJQ.G",
                            Role = 2
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.AttendenceRecord", b =>
                {
                    b.HasOne("LeaveManagementSystem.Core.Entities.User", "Employee")
                        .WithMany("AttendenceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.LeaveBalance", b =>
                {
                    b.HasOne("LeaveManagementSystem.Core.Entities.User", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Core.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.LeaveRequest", b =>
                {
                    b.HasOne("LeaveManagementSystem.Core.Entities.User", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Core.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("LeaveManagementSystem.Core.Entities.Permissions", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.User", b =>
                {
                    b.HasOne("LeaveManagementSystem.Core.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Core.Entities.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.LeaveType", b =>
                {
                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.Permissions", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LeaveManagementSystem.Core.Entities.User", b =>
                {
                    b.Navigation("AttendenceRecords");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
